sudo: false
language: node_js
before_install:
- mkdir ./tests/configuration
node_js:
- '0.12'
- '4'
- '5'
- '6'
script:
- npm run-script coveralls
after_script:
- export GOOGLE_APPLICATION_CREDENTIALS=null
- export STUBBED_API_KEY=null
- export GCLOUD_PROJECT=null
- rm -rf tests/configuration
